/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 college-labels.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CollegeLabels(props) {
  const { nodes, materials } = useGLTF('/college-labels.gltf')
  return (
    <group {...props} dispose={null} scale={0.2}>
      <mesh geometry={nodes['G-__555672'].geometry} material={materials.Heather_Stripe2} position={[1705.17, 27.48, -2055.98]} />
      <mesh geometry={nodes['G-__555681'].geometry} material={materials.Heather_Stripe2} position={[1561.72, 49.52, -2309.53]} />
      <mesh geometry={nodes['G-__555690'].geometry} material={materials.Heather_Stripe2} position={[1805.85, 25.15, -1907.27]} />
      <mesh geometry={nodes['G-__555699'].geometry} material={materials.Heather_Stripe2} position={[1878.23, 45.27, -1980.37]} />
      <mesh geometry={nodes['G-__555708'].geometry} material={materials.Heather_Stripe2} position={[1714.3, 24.54, -2024.73]} />
      <mesh geometry={nodes['G-__555717'].geometry} material={materials.Heather_Stripe2} position={[2203.22, 22.14, -1718.44]} />
      <mesh geometry={nodes['G-__555726'].geometry} material={materials.Heather_Stripe2} position={[2243.61, 33.75, -1624.13]} />
      <mesh geometry={nodes['G-__555735'].geometry} material={materials.Heather_Stripe2} position={[1763.37, 33.06, -2106.96]} />
      <mesh geometry={nodes['G-__555744'].geometry} material={materials.Heather_Stripe2} position={[1760.24, 37.19, -1970.2]} />
      <mesh geometry={nodes['G-__555753'].geometry} material={materials.Heather_Stripe2} position={[1560.44, 54.94, -2173.11]} />
      <mesh geometry={nodes['G-__555762'].geometry} material={materials.Heather_Stripe2} position={[1701.69, 21.06, -2217.4]} />
    </group>
  )
}

useGLTF.preload('/college-labels.gltf')
