/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 model.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.gltf')
  return (
    <group {...props} dispose={null} scale={0.2}>
      <mesh geometry={nodes.AM113_048_Acer_platanoides_Defintion.geometry} material={materials.AM113_048_Acer_platanoides_Bark} position={[1950.05, 0.07, -1578.58]} rotation={[0, -0.98, 0]} scale={0.28} />
      <mesh geometry={nodes.AM113_048_Acer_platanoides_Defintion001.geometry} material={materials.AM113_048_Acer_platanoides_Bark} position={[1962.72, 0.07, -1546.09]} rotation={[0, -0.98, 0]} scale={0.28} />
      <mesh geometry={nodes.AM113_048_Acer_platanoides_Defintion002.geometry} material={materials.AM113_048_Acer_platanoides_Bark} position={[1985.46, 0.07, -1569.52]} rotation={[0, -0.98, 0]} scale={0.28} />
      <mesh geometry={nodes.AM113_048_Acer_platanoides_Defintion003.geometry} material={materials.AM113_048_Acer_platanoides_Bark} position={[2291.29, 0.07, -1508.45]} rotation={[0, -0.98, 0]} scale={0.28} />
      <mesh geometry={nodes.AM113_048_Acer_platanoides_Defintion004.geometry} material={materials.AM113_048_Acer_platanoides_Bark} position={[2324.42, 0.07, -1510.15]} rotation={[0, -0.98, 0]} scale={0.28} />
      <mesh geometry={nodes.AM113_048_Acer_platanoides_Defintion005.geometry} material={materials.AM113_048_Acer_platanoides_Bark} position={[2354.83, 0.07, -1487.12]} rotation={[0, -0.98, 0]} scale={0.28} />
      <mesh geometry={nodes.AM113_048_Acer_platanoides_Defintion006.geometry} material={materials.AM113_048_Acer_platanoides_Bark} position={[2354.97, 0.07, -1440.32]} rotation={[0, -0.98, 0]} scale={0.28} />
      <mesh geometry={nodes.AM113_048_Acer_platanoides_Defintion1.geometry} material={materials.AM113_048_Acer_platanoides} position={[1950.05, 0.07, -1578.58]} rotation={[0, -0.98, 0]} scale={0.23} />
      <mesh geometry={nodes.AM113_048_Acer_platanoides_Defintion1001.geometry} material={materials.AM113_048_Acer_platanoides} position={[1962.72, 0.07, -1546.09]} rotation={[0, -0.98, 0]} scale={0.23} />
      <mesh geometry={nodes.AM113_048_Acer_platanoides_Defintion1002.geometry} material={materials.AM113_048_Acer_platanoides} position={[1985.46, 0.07, -1569.52]} rotation={[0, -0.98, 0]} scale={0.23} />
      <mesh geometry={nodes.AM113_048_Acer_platanoides_Defintion1003.geometry} material={materials.AM113_048_Acer_platanoides} position={[2291.29, 0.07, -1508.45]} rotation={[0, -0.98, 0]} scale={0.23} />
      <mesh geometry={nodes.AM113_048_Acer_platanoides_Defintion1004.geometry} material={materials.AM113_048_Acer_platanoides} position={[2324.42, 0.07, -1510.15]} rotation={[0, -0.98, 0]} scale={0.23} />
      <mesh geometry={nodes.AM113_048_Acer_platanoides_Defintion1005.geometry} material={materials.AM113_048_Acer_platanoides} position={[2354.83, 0.07, -1487.12]} rotation={[0, -0.98, 0]} scale={0.23} />
      <mesh geometry={nodes.AM113_048_Acer_platanoides_Defintion1006.geometry} material={materials.AM113_048_Acer_platanoides} position={[2354.97, 0.07, -1440.32]} rotation={[0, -0.98, 0]} scale={0.23} />
      <mesh geometry={nodes.Sketchup_1.geometry} material={materials.Material} />
      <mesh geometry={nodes.Sketchup_2.geometry} material={materials.Material4} />
      <mesh geometry={nodes.Sketchup_3.geometry} material={materials.Material5} />
      <mesh geometry={nodes.Sketchup_4.geometry} material={materials.Material7} />
      <mesh geometry={nodes.Sketchup_5.geometry} material={materials.Material6} />
      <mesh geometry={nodes.Sketchup_6.geometry} material={materials.Material3} />
      <mesh geometry={nodes.Sketchup_7.geometry} material={materials['[Roofing Scalloped Ornate]']} />
      <mesh geometry={nodes.Sketchup_8.geometry} material={materials['[Grass Dark Green]']} />
      <mesh geometry={nodes.Sketchup_9.geometry} material={materials.Heather_Hair2} />
      <mesh geometry={nodes.Sketchup_10.geometry} material={materials['<Black>']} />
      <mesh geometry={nodes.Sketchup_11.geometry} material={materials.Heather_Shirt} />
    </group>
  )
}

useGLTF.preload('/model.gltf')
