/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 openspaces-labels.gltf
*/

import React, { useRef, useLayoutEffect } from 'react'
import { useGLTF, Text } from '@react-three/drei'

export function OpenSpacesLabels(props) {
  const { nodes, materials } = useGLTF('/openspaces-labels.gltf');
  const labelsRef = useRef([]);

  useLayoutEffect(() => {
    labelsRef.current.forEach((label) => {
      label.lookAt(0, 0, 275)
    })
  })
  return (
    <group {...props} dispose={null} scale={0.2}>
      <mesh geometry={nodes['G-__555645'].geometry} material={materials.Heather_Shirt} position={[1734.03, 11.31, -1361.33]}><Text fontSize={7} color={'brown'} fontWeight={'bold'} style={{ fontWeight: 'bold', fontStyle: 'italic' }} position={[10, 25, -9]} ref={(ref) => labelsRef.current[0] = ref}>Label</Text></mesh>
      <mesh geometry={nodes['G-__555654'].geometry} material={materials.Heather_Shirt} position={[1968.04, 11.49, -1910.13]}><Text fontSize={7} color={'brown'} fontWeight={'bold'} style={{ fontWeight: 'bold', fontStyle: 'italic' }} position={[10, 25, -9]} ref={(ref) => labelsRef.current[0] = ref}>Label</Text></mesh>
      <mesh geometry={nodes['G-__555663'].geometry} material={materials.Heather_Shirt} position={[2275.27, 13.75, -2295.94]}><Text fontSize={7} color={'brown'} fontWeight={'bold'} style={{ fontWeight: 'bold', fontStyle: 'italic' }} position={[10, 25, -9]} ref={(ref) => labelsRef.current[0] = ref}>Label</Text></mesh>
    </group>
  )
}

useGLTF.preload('/openspaces-labels.gltf')
