/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 roads-labels.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RoadsLabels(props) {
  const { nodes, materials } = useGLTF('/roads-labels.gltf')
  return (
    <group {...props} dispose={null} scale={0.2}>
      <mesh geometry={nodes.Makerere_Hill_Rd.geometry} material={materials.Material} position={[2221.73, 0, -1289.48]} rotation={[0, Math.PI / 6, 0]} scale={24.2} />
      <mesh geometry={nodes.Makerere_Hill_Rd001.geometry} material={materials.Material} position={[2335.94, 0, -1355.26]} rotation={[0, Math.PI / 6, 0]} scale={24.2} />
      <mesh geometry={nodes.Makerere_Hill_Rd002.geometry} material={materials.Material} position={[2014.96, 0, -1249.37]} rotation={[0, 0.16, 0]} scale={24.2} />
      <mesh geometry={nodes.Makerere_Hill_Rd003.geometry} material={materials.Material} position={[1827.42, 0, -1229.69]} rotation={[0, 0.09, 0]} scale={24.2} />
      <mesh geometry={nodes.Makerere_Hill_Rd004.geometry} material={materials.Material} position={[1690, 0, -1241.57]} rotation={[0, -0.12, 0]} scale={24.2} />
      <mesh geometry={nodes.University_Rd.geometry} material={materials.Material} position={[2212.64, 0, -1583.75]} rotation={[0, -Math.PI / 3, 0]} scale={14.28} />
      <mesh geometry={nodes.University_Rd001.geometry} material={materials.Material} position={[2171.43, 0, -1638.1]} rotation={[0, -0.89, 0]} scale={14.28} />
      <mesh geometry={nodes.University_Rd002.geometry} material={materials.Material} position={[2124.87, 0, -1696.18]} rotation={[0, -0.91, 0]} scale={14.28} />
      <mesh geometry={nodes.University_Rd003.geometry} material={materials.Material} position={[2075.33, 0, -1732.17]} rotation={[0, -0.55, 0]} scale={14.28} />
      <mesh geometry={nodes.University_Rd004.geometry} material={materials.Material} position={[2005.43, 0, -1798.92]} rotation={[0, -0.86, 0]} scale={14.28} />
      <mesh geometry={nodes.University_Rd005.geometry} material={materials.Material} position={[1934.04, 0, -1882.54]} rotation={[0, -0.87, 0]} scale={14.28} />
      <mesh geometry={nodes.University_Rd006.geometry} material={materials.Material} position={[1870.03, 0, -1957.65]} rotation={[0, -0.87, 0]} scale={14.28} />
      <mesh geometry={nodes.Pool_Rd.geometry} material={materials.Material} position={[2272.15, 0, -1549.77]} rotation={[0, 1.29, 0]} scale={16.27} />
      <mesh geometry={nodes.Pool_Rd001.geometry} material={materials.Material} position={[2300.26, 0, -1643.56]} rotation={[0, 1.44, 0]} scale={16.27} />
      <mesh geometry={nodes.Pool_Rd002.geometry} material={materials.Material} position={[2250.15, 0, -1761.85]} rotation={[-Math.PI, 1, -Math.PI]} scale={16.27} />
      <mesh geometry={nodes.Pool_Rd003.geometry} material={materials.Material} position={[2153.35, 0, -1872.46]} rotation={[-Math.PI, 0.79, -Math.PI]} scale={16.27} />
      <mesh geometry={nodes.Pool_Rd004.geometry} material={materials.Material} position={[2105.79, 0, -1959.88]} rotation={[-Math.PI, 1.15, -Math.PI]} scale={16.27} />
      <mesh geometry={nodes.Pool_Rd005.geometry} material={materials.Material} position={[2041.99, 0, -2105.9]} rotation={[-Math.PI, 1.14, -Math.PI]} scale={16.27} />
      <mesh geometry={nodes.Livingstone_Rd.geometry} material={materials.Material} position={[1994.58, 0, -2204.29]} rotation={[-Math.PI, 1.15, -Math.PI]} scale={14.19} />
      <mesh geometry={nodes.Livingstone_Rd001.geometry} material={materials.Material} position={[1948.2, 0, -2308.32]} rotation={[-Math.PI, 1.15, -Math.PI]} scale={14.19} />
      <mesh geometry={nodes.Observatory_Hill.geometry} material={materials.Material} position={[1859.88, 0, -2376.2]} rotation={[Math.PI, -0.15, Math.PI]} scale={14.82} />
      <mesh geometry={nodes.Observatory_Hill001.geometry} material={materials.Material} position={[1740.26, 0, -2315.96]} rotation={[Math.PI, -1.5, Math.PI]} scale={14.82} />
      <mesh geometry={nodes.Garden_Hill_Rd.geometry} material={materials.Material} position={[1905.66, 0, -2284.25]} rotation={[Math.PI, -0.26, Math.PI]} scale={22.57} />
      <mesh geometry={nodes.Quarry_Stone_Rd.geometry} material={materials.Material} position={[1842.82, 0, -2107.05]} rotation={[-Math.PI, 1.13, -Math.PI]} scale={26.51} />
      <mesh geometry={nodes.Northcote_Rd.geometry} material={materials.Material} position={[1916.57, 0, -2086.72]} rotation={[0, 0.72, 0]} scale={24.84} />
      <mesh geometry={nodes.Northcote_Rd001.geometry} material={materials.Material} position={[2080.79, 0, -2230.28]} rotation={[0, 0.36, 0]} scale={24.84} />
      <mesh geometry={nodes.Northcote_Rd002.geometry} material={materials.Material} position={[2179.24, 0, -2255.91]} rotation={[0, -0.4, 0]} scale={24.84} />
      <mesh geometry={nodes.Northcote_Rd003.geometry} material={materials.Material} position={[2285.78, 0, -2128.71]} rotation={[0, -1.19, 0]} scale={24.84} />
      <mesh geometry={nodes.Tennis_Ct_Rd.geometry} material={materials.Material} position={[2124.49, 0, -1503.88]} rotation={[0, 0.07, 0]} scale={18.57} />
      <mesh geometry={nodes.Tennis_Ct_Rd001.geometry} material={materials.Material} position={[1978.23, 0, -1466]} rotation={[0, 0.27, 0]} scale={18.57} />
      <mesh geometry={nodes.Mary_Stuart_Rd.geometry} material={materials.Material} position={[1885.28, 0, -1527.21]} rotation={[-Math.PI, 1.1, -Math.PI]} scale={14.45} />
      <mesh geometry={nodes.Mary_Stuart_Rd001.geometry} material={materials.Material} position={[1827.28, 0, -1675.33]} rotation={[-Math.PI, 1.28, -Math.PI]} scale={14.45} />
      <mesh geometry={nodes.Kasubi_Westlink_.geometry} material={materials.Material} position={[1694.55, 0, -1743.26]} rotation={[0, 0.19, 0]} scale={16.59} />
      <mesh geometry={nodes.West_Rd.geometry} material={materials.Material} position={[1540.95, 0, -2007.5]} rotation={[0, -1.17, 0]} scale={22.25} />
      <mesh geometry={nodes.West_Rd001.geometry} material={materials.Material} position={[1580.55, 0, -1910.65]} rotation={[0, -1.17, 0]} scale={22.25} />
      <mesh geometry={nodes.West_Rd002.geometry} material={materials.Material} position={[1621.47, 0, -1765.81]} rotation={[0, -1.38, 0]} scale={22.25} />
      <mesh geometry={nodes.Mansfield_Rd.geometry} material={materials.Material} position={[1618.51, 0, -2098.35]} rotation={[Math.PI, -0.18, Math.PI]} scale={23.11} />
      <mesh geometry={nodes.Cassia_Hill_Rd.geometry} material={materials.Material} position={[2379.9, 0, -1944.53]} rotation={[0, -1.39, 0]} scale={20.71} />
      <mesh geometry={nodes.Cassia_Hill_Rd001.geometry} material={materials.Material} position={[2341.64, 0, -1842.01]} rotation={[Math.PI, -0.34, Math.PI]} scale={20.71} />
    </group>
  )
}

useGLTF.preload('/roads-labels.gltf')
