/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 trees-model.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TreesModel(props) {
  const { nodes, materials } = useGLTF('/trees-model.gltf')
  return (
    <group {...props} dispose={null} scale={0.2}>
      <mesh geometry={nodes.AM113_048_Acer_platanoides_Defintion.geometry} material={materials.AM113_048_Acer_platanoides_Bark} scale={0.28} />
      <mesh geometry={nodes.AM113_048_Acer_platanoides_Defintion1.geometry} material={materials.AM113_048_Acer_platanoides} scale={0.23} />
      <mesh geometry={nodes.DUPLI_Group4.geometry} material={nodes.DUPLI_Group4.material} position={[2274.27, 0.07, -1450.7]} />
    </group>
  )
}

useGLTF.preload('/trees-model.gltf')
